/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    // TomEE already provides JSF and Weld - exclude from WAR
    compileOnly("org.glassfish:jakarta.faces:4.0.4")
    compileOnly("org.jboss.weld.servlet:weld-servlet-shaded:5.1.0.Final")
    compileOnly("jakarta.platform:jakarta.jakartaee-api:10.0.0")
    // H2 database for embedded database
    //implementation("com.h2database:h2:2.2.224")
    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation("at.favre.lib:bcrypt:0.10.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(19)
    }
}



tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
tasks.war {
    from("src/main/webapp")
}

